// This File has been authored by AllTheMods Staff, or a Community contributor for use in AllTheMods - AllTheMods 10.
// As all AllTheMods packs are licensed under All Rights Reserved, this file is not allowed to be used in any public packs not released by the AllTheMods Team, without explicit permission.

ServerEvents.recipes(allthemods => {
    //Modularium
        allthemods.recipes.modular_machinery_reborn.machine_recipe('atm:auto_hepheastus_forge', 100)
            .requireEnergy(12288, 8, 18)
            .requireFluid('5000x kubejs:liquid_aureal', 31, 8)
            .requireFluid('1000x kubejs:liquid_souls', 31, 27)
            .requireFluid('5000x evilcraft:blood', 31, 46)
            .requireFluid('1000x justdirethings:xp_fluid_source', 31, 65)
            .requireItem('allthemodium:allthemodium_ingot', 54, 18)
            .requireItem('4x forbidden_arcanus:deorum_ingot', 54, 37)
            .requireItem('4x enderio:end_steel_ingot', 54, 56)
            .progressX(90)
            .progressY(37)
            .produceItem('24x modular_machinery_reborn:modularium', 130, 37)
            .width(154)
            .height(106)

        allthemods.recipes.modular_machinery_reborn.machine_recipe('atm:auto_hepheastus_forge', 100)
            .requireEnergy(12288, 8, 18)
            .requireFluid('5000x kubejs:liquid_aureal', 31, 8)
            .requireFluid('1000x kubejs:liquid_souls', 31, 27)
            .requireFluid('5000x evilcraft:blood', 31, 46)
            .requireFluid('1000x justdirethings:xp_fluid_source', 31, 65)
            .requireItem('allthemodium:vibranium_ingot', 54, 18)
            .requireItem('4x forbidden_arcanus:deorum_ingot', 54, 37)
            .requireItem('4x enderio:end_steel_ingot', 54, 56)
            .progressX(90)
            .progressY(37)
            .produceItem('36x modular_machinery_reborn:modularium', 130, 37)
            .width(154)
            .height(106)

        allthemods.recipes.modular_machinery_reborn.machine_recipe('atm:auto_hepheastus_forge', 100)
            .requireEnergy(12288, 8, 18)
            .requireFluid('5000x kubejs:liquid_aureal', 31, 8)
            .requireFluid('1000x kubejs:liquid_souls', 31, 27)
            .requireFluid('5000x evilcraft:blood', 31, 46)
            .requireFluid('1000x justdirethings:xp_fluid_source', 31, 65)
            .requireItem('allthemodium:unobtainium_ingot', 54, 18)
            .requireItem('4x forbidden_arcanus:deorum_ingot', 54, 37)
            .requireItem('4x enderio:end_steel_ingot', 54, 56)
            .progressX(90)
            .progressY(37)
            .produceItem('48x modular_machinery_reborn:modularium', 130, 37)
            .width(154)
            .height(106)

    //Prisms
        //Sea
            allthemods.recipes.modular_machinery_reborn.machine_recipe('atm:auto_hepheastus_forge', 100)
                .requireEnergy(12288, 8, 9)
                .requireFluid('1000x kubejs:liquid_aureal', 31, 8)
                .requireFluid('80x kubejs:liquid_souls', 31, 27)
                .requireFluid('20000x evilcraft:blood', 31, 46)
                .requireItem('2x minecraft:prismarine_shard', 54, 8)
                .requireItem('2x minecraft:turtle_scute', 54, 27)
                .requireItem('2x minecraft:lapis_lazuli', 54, 46)
                .requireItem('minecraft:heart_of_the_sea', 73, 27)
                .progressX(109)
                .progressY(27)
                .produceItem('forbidden_arcanus:sea_prism', 149, 27)
                .width(172)
                .height(90)
        
        //Smelter
            allthemods.recipes.modular_machinery_reborn.machine_recipe('atm:auto_hepheastus_forge', 100)
                .requireEnergy(12288, 8, 9)
                .requireFluid('2000x kubejs:liquid_aureal', 31, 8)
                .requireFluid('400x kubejs:liquid_souls', 31, 27)
                .requireFluid('12500x evilcraft:blood', 31, 46)
                .requireItem('2x minecraft:coal', 54, 8)
                .requireItem('forbidden_arcanus:arcane_crystal_block', 54, 27)
                .requireItem('3x minecraft:blaze_powder', 54, 46)
                .progressX(90)
                .progressY(27)
                .produceItem('forbidden_arcanus:smelter_prism', 130, 27)
                .width(156)
                .height(90)
    
        //Terra
            allthemods.recipes.modular_machinery_reborn.machine_recipe('atm:auto_hepheastus_forge', 100)
                .requireEnergy(12288, 8, 9)
                .requireFluid('3000x kubejs:liquid_aureal', 31, 8)
                .requireFluid('90x kubejs:liquid_souls', 31, 27)
                .requireFluid('15000x evilcraft:blood', 31, 46)
                .requireItem('2x minecraft:flint', 54, 8)
                .requireItem('2x minecraft:dripstone_block', 54, 27)
                .requireItem('2x minecraft:pointed_dripstone', 54, 46)
                .requireItem('minecraft:diamond_block', 73, 27)
                .progressX(109)
                .progressY(27)
                .produceItem('forbidden_arcanus:terrastomp_prism', 149, 27)
                .width(172)
                .height(90)
        //Whirlwind
            allthemods.recipes.modular_machinery_reborn.machine_recipe('atm:auto_hepheastus_forge', 100)
                .requireEnergy(12288, 8, 9)
                .requireFluid('10000x kubejs:liquid_aureal', 31, 8)
                .requireFluid('30x kubejs:liquid_souls', 31, 27)
                .requireFluid('22500x evilcraft:blood', 31, 46)
                .requireItem('forbidden_arcanus:bat_wing', 54, 8)
                .requireItem('2x minecraft:feather', 54, 27)
                .requireItem('3x minecraft:phantom_membrane', 54, 46)
                .requireItem('minecraft:white_wool', 73, 27)
                .progressX(109)
                .progressY(27)
                .produceItem('forbidden_arcanus:whirlwind_prism', 149, 27)
                .width(172)
                .height(90)
        //Soul
            allthemods.recipes.modular_machinery_reborn.machine_recipe('atm:auto_hepheastus_forge', 100)
                .requireEnergy(12288, 8, 18)
                .requireFluid('15000x kubejs:liquid_aureal', 31, 8)
                .requireFluid('200x kubejs:liquid_souls', 31, 27)
                .requireFluid('3750x evilcraft:blood', 31, 46)
                .requireFluid('2200x justdirethings:xp_fluid_source', 31, 65)
                .requireItem('forbidden_arcanus:soul', 54, 18)
                .requireItem('forbidden_arcanus:corrupt_soul', 54, 37)
                .requireItem('forbidden_arcanus:enchanted_soul', 54, 56)
                .requireItem('2x minecraft:amethyst_shard', 73, 18)
                .requireItem('minecraft:quartz', 73, 37)
                .requireItem('3x forbidden_arcanus:ender_pearl_fragment', 73, 56)
                .progressX(109)
                .progressY(37)
                .produceItem('forbidden_arcanus:soul_binding_crystal', 149, 37)
                .width(172)
                .height(106)

        //Quantum Injector
            allthemods.recipes.modular_machinery_reborn.machine_recipe('atm:auto_hepheastus_forge', 100)
                .requireEnergy(12288, 8, 18)
                .requireFluid('50000x kubejs:liquid_aureal', 31, 8)
                .requireFluid('500x kubejs:liquid_souls', 31, 27)
                .requireFluid('30000x evilcraft:blood', 31, 46)
                .requireFluid('10600x justdirethings:xp_fluid_source', 31, 65)
                .requireItem('forbidden_arcanus:mundabitur_dust', 54, 27)
                .requireItem('4x forbidden_arcanus:quantum_core', 54, 46)
                .progressX(90)
                .progressY(37)
                .produceItem('forbidden_arcanus:quantum_injector', 130, 37)
                .width(156)
                .height(106)
})

// This File has been authored by AllTheMods Staff, or a Community contributor for use in AllTheMods - AllTheMods 10.
// As all AllTheMods packs are licensed under All Rights Reserved, this file is not allowed to be used in any public packs not released by the AllTheMods Team, without explicit permission.