[Gui]
	#The x-coordinate of the accessories button in the inventory and accessories menus
	"Button x-coordinate in inventory menus" = 28
	#The x-coordinate of the accessories button in the accessories menu
	"Button x-coordinate in accessories menu" = 10
