#These settings only affects client
[Client]
	#The vertical pixel distance from the origin point of player inventoy gui
	# Default: 67
	# Range: > -2147483648
	CosArmorGuiButton_Top = 68
	#The horizontal pixel distance from the origin point of player inventory gui
	# Default: 59
	# Range: > -2147483648
	CosArmorToggleButton_Left = 60
	#The horizontal pixel distance from the origin point of creative inventory gui
	# Default: 95
	# Range: > -2147483648
	CosArmorCreativeGuiButton_Left = 96
	#The vertical pixel distance from the origin point of creative inventoy gui
	# Default: 38
	# Range: > -2147483648
	CosArmorCreativeGuiButton_Top = 40
