#Client only settings, mostly things related to rendering
[client]
	#The X-Offset for the Creative Curios GUI button
	# Default: 0
	# Range: -100 ~ 100
	creativeButtonXOffset = -1
	#The Y-Offset for the Creative Curios GUI button
	# Default: 0
	# Range: -100 ~ 100
	creativeButtonYOffset = -1
