[Client]
	#Changes the rendertype for lava to fix lava being visible inside boats. This is a potential performance hit and it's recommended to turn of on low end systems.
	changeLavaRenderType = false
