
#A list of preferred Mod IDs that results of IE processes should stem from, aka which mod you want the copper to come from.
#This affects the ores dug by the excavator, as well as those crushing recipes that don't have associated IE items. This list is in oreder of priority.
preferredOres = [    "minecraft",
    "alltheores",
    "allthemodium",
    "kubejs",
    "mekanism",
    "modern_industrialization",
    "occultism",
    "industrialforegoing",
    "pneumaticcraft",
    "biggerreactors", 
    "ae2",
    "enderio",
    "utilitarian",
    "actuallyadditions"]
