[tiny]
	#Defines the source tank size
	# Default: 100
	# Range: > 1
	size = 1000

[small]
	#Defines the source tank size
	# Default: 400
	# Range: > 1
	size = 4000

[normal]
	#Defines the source tank size
	# Default: 1000
	# Range: > 1
	size = 10000

[reinforced]
	#Defines the source tank size
	# Default: 2000
	# Range: > 1
	size = 20000

[big]
	#Defines the source tank size
	# Default: 4500
	# Range: > 1
	size = 45000

[huge]
	#Defines the source tank size
	# Default: 8000
	# Range: > 1
	size = 800000

[ludicrous]
	#Defines the source tank size
	# Default: 16000
	# Range: > 1
	size = 1600000

[vacuum]
	#Defines the source tank size
	# Default: 32000
	# Range: > 1
	size = 3200000
