#Render multiblock placement preview
showMachinePreview = true
#Enable help button in machine UIs
enableHelpButton = true
#Maximum zipline speed in blocks/second
# Default: 8.0
# Range: 0.0 ~ 100.0
maxZiplineSpeed = 8.0
#Zipline acceleration, higher = faster
# Default: 0.1
# Range: 0.0 ~ 10.0
ziplineAcceleration = 0.1
#Enable auto jump at zipline end
ziplineAutoJump = true
#Enable 3rd person camera while ziplining
ziplineCameraSwitch = true
