ServerEvents.recipes(allthemods => {

    if (Platform.isLoaded('modular_machinery_reborn')) {
        allthemods.recipes.modern_industrialization.auto_forge(1024, 100)
            .fluidIn('5000x kubejs:liquid_aureal')
            .fluidIn('1000x kubejs:liquid_souls')
            .fluidIn('5000x evilcraft:blood')
            .fluidIn('1000x #c:experience')
            .itemIn('enderio:end_steel_ingot')
            .itemIn('forbidden_arcanus:deorum_ingot')
            .itemIn('forbidden_arcanus:deorum_ingot')
            .itemIn('enderio:end_steel_ingot')
            .itemIn('allthemodium:allthemodium_ingot')
            .itemIn('forbidden_arcanus:deorum_ingot')
            .itemIn('enderio:end_steel_ingot')
            .itemIn('enderio:end_steel_ingot')
            .itemIn('forbidden_arcanus:deorum_ingot')
            .itemOut('24x modular_machinery_reborn:modularium')

        allthemods.recipes.modern_industrialization.auto_forge(1024, 100)
            .fluidIn('5000x kubejs:liquid_aureal')
            .fluidIn('1000x kubejs:liquid_souls')
            .fluidIn('5000x evilcraft:blood')
            .fluidIn('1000x #c:experience')
            .itemIn('enderio:end_steel_ingot')
            .itemIn('forbidden_arcanus:deorum_ingot')
            .itemIn('forbidden_arcanus:deorum_ingot')
            .itemIn('enderio:end_steel_ingot')
            .itemIn('allthemodium:vibranium_ingot')
            .itemIn('forbidden_arcanus:deorum_ingot')
            .itemIn('enderio:end_steel_ingot')
            .itemIn('enderio:end_steel_ingot')
            .itemIn('forbidden_arcanus:deorum_ingot')
            .itemOut('32x modular_machinery_reborn:modularium')

        allthemods.recipes.modern_industrialization.auto_forge(1024, 100)
            .fluidIn('5000x kubejs:liquid_aureal')
            .fluidIn('1000x kubejs:liquid_souls')
            .fluidIn('5000x evilcraft:blood')
            .fluidIn('1000x #c:experience')
            .itemIn('enderio:end_steel_ingot')
            .itemIn('forbidden_arcanus:deorum_ingot')
            .itemIn('forbidden_arcanus:deorum_ingot')
            .itemIn('enderio:end_steel_ingot')
            .itemIn('allthemodium:unobtainium_ingot')
            .itemIn('forbidden_arcanus:deorum_ingot')
            .itemIn('enderio:end_steel_ingot')
            .itemIn('enderio:end_steel_ingot')
            .itemIn('forbidden_arcanus:deorum_ingot')
            .itemOut('48x modular_machinery_reborn:modularium')
    }

    allthemods.recipes.modern_industrialization.auto_forge(1024, 100)
        .fluidIn('1000x kubejs:liquid_aureal')
        .fluidIn('80x kubejs:liquid_souls')
        .fluidIn('20000x evilcraft:blood')
        .itemIn('minecraft:heart_of_the_sea')
        .itemIn('2x minecraft:prismarine_shard')
        .itemIn('2x minecraft:turtle_scute')
        .itemIn('2x minecraft:lapis_lazuli')
        .itemOut('forbidden_arcanus:sea_prism')

    allthemods.recipes.modern_industrialization.auto_forge(1024, 100)
        .fluidIn('2000x kubejs:liquid_aureal')
        .fluidIn('400x kubejs:liquid_souls')
        .fluidIn('12500x evilcraft:blood')
        .itemIn('forbidden_arcanus:arcane_crystal_block')
        .itemIn('2x minecraft:coal')
        .itemIn('3x minecraft:blaze_powder')
        .itemOut('forbidden_arcanus:smelter_prism')

    allthemods.recipes.modern_industrialization.auto_forge(1024, 100)
        .fluidIn('3000x kubejs:liquid_aureal')
        .fluidIn('90x kubejs:liquid_souls')
        .fluidIn('15000x evilcraft:blood')
        .itemIn('minecraft:diamond_block')
        .itemIn('2x minecraft:flint')
        .itemIn('2x minecraft:dripstone_block')
        .itemIn('2x minecraft:pointed_dripstone')
        .itemOut('forbidden_arcanus:terrastomp_prism')

    allthemods.recipes.modern_industrialization.auto_forge(1024, 100)
        .fluidIn('10000x kubejs:liquid_aureal')
        .fluidIn('30x kubejs:liquid_souls')
        .fluidIn('22500x evilcraft:blood')
        .itemIn('minecraft:white_wool')
        .itemIn('forbidden_arcanus:bat_wing')
        .itemIn('2x minecraft:feather')
        .itemIn('3x minecraft:phantom_membrane')
        .itemOut('forbidden_arcanus:whirlwind_prism')

    allthemods.recipes.modern_industrialization.auto_forge(1024, 100)
        .fluidIn('15000x kubejs:liquid_aureal')
        .fluidIn('200x kubejs:liquid_souls')
        .fluidIn('3750x evilcraft:blood')
        .fluidIn('2200x #c:experience')
        .itemIn('minecraft:quartz')
        .itemIn('forbidden_arcanus:soul')
        .itemIn('forbidden_arcanus:corrupt_soul')
        .itemIn('forbidden_arcanus:enchanted_soul')
        .itemIn('2x minecraft:amethyst_shard')
        .itemIn('3x forbidden_arcanus:ender_pearl_fragment')
        .itemOut('forbidden_arcanus:soul_binding_crystal')

    allthemods.recipes.modern_industrialization.auto_forge(1024, 100)
        .fluidIn('50000x kubejs:liquid_aureal')
        .fluidIn('500x kubejs:liquid_souls')
        .fluidIn('30000x evilcraft:blood')
        .fluidIn('10600x #c:experience')
        .itemIn('forbidden_arcanus:mundabitur_dust')
        .itemIn('4x forbidden_arcanus:quantum_core')
        .itemOut('forbidden_arcanus:quantum_injector')
})