ServerEvents.recipes(allthemods => {

    if (Platform.isLoaded('modular_machinery_reborn')) {
        allthemods.recipes.modern_industrialization.auto_forge(1024, 100)
            .fluidIn('5000x kubejs:liquid_aureal')
            .fluidIn('1000x kubejs:liquid_souls')
            .fluidIn('5000x evilcraft:blood')
            .fluidIn('1000x #c:experience')
            .itemIn('enderio:end_steel_ingot')
            .itemIn('forbidden_arcanus:deorum_ingot')
            .itemIn('forbidden_arcanus:deorum_ingot')
            .itemIn('enderio:end_steel_ingot')
            .itemIn('allthemodium:allthemodium_ingot')
            .itemIn('forbidden_arcanus:deorum_ingot')
            .itemIn('enderio:end_steel_ingot')
            .itemIn('enderio:end_steel_ingot')
            .itemIn('forbidden_arcanus:deorum_ingot')
            .itemOut('24x modular_machinery_reborn:modularium')

        allthemods.recipes.modern_industrialization.auto_forge(1024, 100)
            .fluidIn('5000x kubejs:liquid_aureal')
            .fluidIn('1000x kubejs:liquid_souls')
            .fluidIn('5000x evilcraft:blood')
            .fluidIn('1000x #c:experience')
            .itemIn('enderio:end_steel_ingot')
            .itemIn('forbidden_arcanus:deorum_ingot')
            .itemIn('forbidden_arcanus:deorum_ingot')
            .itemIn('enderio:end_steel_ingot')
            .itemIn('allthemodium:vibranium_ingot')
            .itemIn('forbidden_arcanus:deorum_ingot')
            .itemIn('enderio:end_steel_ingot')
            .itemIn('enderio:end_steel_ingot')
            .itemIn('forbidden_arcanus:deorum_ingot')
            .itemOut('32x modular_machinery_reborn:modularium')

        allthemods.recipes.modern_industrialization.auto_forge(1024, 100)
            .fluidIn('5000x kubejs:liquid_aureal')
            .fluidIn('1000x kubejs:liquid_souls')
            .fluidIn('5000x evilcraft:blood')
            .fluidIn('1000x #c:experience')
            .itemIn('enderio:end_steel_ingot')
            .itemIn('forbidden_arcanus:deorum_ingot')
            .itemIn('forbidden_arcanus:deorum_ingot')
            .itemIn('enderio:end_steel_ingot')
            .itemIn('allthemodium:unobtainium_ingot')
            .itemIn('forbidden_arcanus:deorum_ingot')
            .itemIn('enderio:end_steel_ingot')
            .itemIn('enderio:end_steel_ingot')
            .itemIn('forbidden_arcanus:deorum_ingot')
            .itemOut('48x modular_machinery_reborn:modularium')
    }

    allthemods.recipes.modern_industrialization.auto_forge(1024, 100)
        .fluidIn('1000x kubejs:liquid_aureal')
        .fluidIn('80x kubejs:liquid_souls')
        .fluidIn('20000x evilcraft:blood')
        .itemIn('minecraft:heart_of_the_sea')
        .itemIn('2x minecraft:prismarine_shard')
        .itemIn('2x minecraft:turtle_scute')
        .itemIn('2x minecraft:lapis_lazuli')
        .itemOut('forbidden_arcanus:sea_prism')

    allthemods.recipes.modern_industrialization.auto_forge(1024, 100)
        .fluidIn('2000x kubejs:liquid_aureal')
        .fluidIn('400x kubejs:liquid_souls')
        .fluidIn('12500x evilcraft:blood')
        .itemIn('forbidden_arcanus:arcane_crystal_block')
        .itemIn('2x minecraft:coal')
        .itemIn('3x minecraft:blaze_powder')
        .itemOut('forbidden_arcanus:smelter_prism')

    allthemods.recipes.modern_industrialization.auto_forge(1024, 100)
        .fluidIn('3000x kubejs:liquid_aureal')
        .fluidIn('90x kubejs:liquid_souls')
        .fluidIn('15000x evilcraft:blood')
        .itemIn('minecraft:diamond_block')
        .itemIn('2x minecraft:flint')
        .itemIn('2x minecraft:dripstone_block')
        .itemIn('2x minecraft:pointed_dripstone')
        .itemOut('forbidden_arcanus:terrastomp_prism')

    allthemods.recipes.modern_industrialization.auto_forge(1024, 100)
        .fluidIn('10000x kubejs:liquid_aureal')
        .fluidIn('30x kubejs:liquid_souls')
        .fluidIn('22500x evilcraft:blood')
        .itemIn('minecraft:white_wool')
        .itemIn('forbidden_arcanus:bat_wing')
        .itemIn('2x minecraft:feather')
        .itemIn('3x minecraft:phantom_membrane')
        .itemOut('forbidden_arcanus:whirlwind_prism')

    allthemods.recipes.modern_industrialization.auto_forge(1024, 100)
        .fluidIn('15000x kubejs:liquid_aureal')
        .fluidIn('200x kubejs:liquid_souls')
        .fluidIn('3750x evilcraft:blood')
        .fluidIn('2200x #c:experience')
        .itemIn('minecraft:quartz')
        .itemIn('forbidden_arcanus:soul')
        .itemIn('forbidden_arcanus:corrupt_soul')
        .itemIn('forbidden_arcanus:enchanted_soul')
        .itemIn('2x minecraft:amethyst_shard')
        .itemIn('3x forbidden_arcanus:ender_pearl_fragment')
        .itemOut('forbidden_arcanus:soul_binding_crystal')

    allthemods.recipes.modern_industrialization.auto_forge(1024, 100)
        .fluidIn('50000x kubejs:liquid_aureal')
        .fluidIn('500x kubejs:liquid_souls')
        .fluidIn('30000x evilcraft:blood')
        .fluidIn('10600x #c:experience')
        .itemIn('forbidden_arcanus:mundabitur_dust')
        .itemIn('4x forbidden_arcanus:quantum_core')
        .itemOut('forbidden_arcanus:quantum_injector')

    allthemods.recipes.modern_industrialization.auto_forge(1024, 100)
        .fluidIn('1000x kubejs:liquid_aureal')
        .fluidIn('320x kubejs:liquid_souls')
        .fluidIn('10000x evilcraft:blood')
        .fluidIn('3000x #c:experience')
        .itemIn('forbidden_arcanus:silver_dragon_scale')
        .itemIn('allthemodium:unobtainium_vibranium_alloy_ingot')
        .itemIn('forbidden_arcanus:golden_dragon_scale')
        .itemIn('forbidden_arcanus:eternal_stella')
        .itemIn('allthemodium:unobtainium_shovel')
        .itemIn('forbidden_arcanus:eternal_stella')
        .itemIn('allthemodium:vibranium_allthemodium_alloy_ingot')
        .itemIn('forbidden_arcanus:aquatic_dragon_scale')
        .itemIn('allthemodium:unobtainium_allthemodium_alloy_ingot')
        .itemOut('allthemodium:alloy_shovel')

    allthemods.recipes.modern_industrialization.auto_forge(1024, 100)
        .fluidIn('1000x kubejs:liquid_aureal')
        .fluidIn('320x kubejs:liquid_souls')
        .fluidIn('10000x evilcraft:blood')
        .fluidIn('3000x #c:experience')
        .itemIn('forbidden_arcanus:silver_dragon_scale')
        .itemIn('allthemodium:unobtainium_vibranium_alloy_ingot')
        .itemIn('forbidden_arcanus:golden_dragon_scale')
        .itemIn('forbidden_arcanus:eternal_stella')
        .itemIn('allthemodium:unobtainium_pickaxe')
        .itemIn('forbidden_arcanus:eternal_stella')
        .itemIn('allthemodium:vibranium_allthemodium_alloy_ingot')
        .itemIn('forbidden_arcanus:aquatic_dragon_scale')
        .itemIn('allthemodium:unobtainium_allthemodium_alloy_ingot')
        .itemOut('allthemodium:alloy_pick')

    allthemods.recipes.modern_industrialization.auto_forge(1024, 100)
        .fluidIn('1000x kubejs:liquid_aureal')
        .fluidIn('320x kubejs:liquid_souls')
        .fluidIn('10000x evilcraft:blood')
        .fluidIn('3000x #c:experience')
        .itemIn('forbidden_arcanus:silver_dragon_scale')
        .itemIn('allthemodium:unobtainium_vibranium_alloy_ingot')
        .itemIn('forbidden_arcanus:golden_dragon_scale')
        .itemIn('forbidden_arcanus:eternal_stella')
        .itemIn('allthemodium:unobtainium_sword')
        .itemIn('forbidden_arcanus:eternal_stella')
        .itemIn('allthemodium:vibranium_allthemodium_alloy_ingot')
        .itemIn('forbidden_arcanus:aquatic_dragon_scale')
        .itemIn('allthemodium:unobtainium_allthemodium_alloy_ingot')
        .itemOut('allthemodium:alloy_sword')

    allthemods.recipes.modern_industrialization.auto_forge(1024, 100)
        .fluidIn('1000x kubejs:liquid_aureal')
        .fluidIn('320x kubejs:liquid_souls')
        .fluidIn('10000x evilcraft:blood')
        .fluidIn('3000x #c:experience')
        .itemIn('forbidden_arcanus:silver_dragon_scale')
        .itemIn('allthemodium:unobtainium_vibranium_alloy_ingot')
        .itemIn('forbidden_arcanus:golden_dragon_scale')
        .itemIn('forbidden_arcanus:eternal_stella')
        .itemIn('allthemodium:unobtainium_axe')
        .itemIn('forbidden_arcanus:eternal_stella')
        .itemIn('allthemodium:vibranium_allthemodium_alloy_ingot')
        .itemIn('forbidden_arcanus:aquatic_dragon_scale')
        .itemIn('allthemodium:unobtainium_allthemodium_alloy_ingot')
        .itemOut('allthemodium:alloy_axe')

    allthemods.recipes.modern_industrialization.auto_forge(1024, 100)
        .fluidIn('1000x kubejs:liquid_aureal')
        .fluidIn('640x kubejs:liquid_souls')
        .fluidIn('20000x evilcraft:blood')
        .fluidIn('6000x #c:experience')
        .itemIn('forbidden_arcanus:smelter_prism')
        .itemIn('allthemodium:alloy_sword')
        .itemIn('forbidden_arcanus:terrastomp_prism')
        .itemIn('allthemodium:alloy_shovel')
        .itemIn('mysticalagradditions:awakened_supremium_paxel')
        .itemIn('allthemodium:alloy_pick')
        .itemIn('forbidden_arcanus:whirlwind_prism')
        .itemIn('allthemodium:alloy_axe')
        .itemIn('forbidden_arcanus:sea_prism')
        .itemOut('allthemodium:alloy_paxel')

    allthemods.recipes.modern_industrialization.auto_forge(1024, 100)
        .fluidIn('820x kubejs:liquid_aureal')
        .fluidIn('10x kubejs:liquid_souls')
        .fluidIn('10000x evilcraft:blood')
        .itemIn('3x forbidden_arcanus:xpetrified_orb')
        .itemIn('forbidden_arcanus:stellarite_piece')
        .itemIn('minecraft:diamond')
        .itemOut('forbidden_arcanus:eternal_stella')

    allthemods.recipes.modern_industrialization.auto_forge(1024, 100)
        .fluidIn('1000x kubejs:liquid_aureal')
        .fluidIn('20x kubejs:liquid_souls')
        .fluidIn('12500x evilcraft:blood')
        .itemIn('2x minecraft:clay_ball')
        .itemIn('2x forbidden_arcanus:wax')
        .itemIn('2x minecraft:slime_ball')
        .itemIn('minecraft:iron_ingot')
        .itemIn('minecraft:lodestone')
        .itemOut('forbidden_arcanus:ferrognetic_mixture')

    allthemods.recipes.modern_industrialization.auto_forge(1024, 100)
        .fluidIn('2000x kubejs:liquid_aureal')
        .fluidIn('50x kubejs:liquid_souls')
        .fluidIn('12000x evilcraft:blood')
        .fluidIn('1550x #c:experience')
        .itemIn('4x forbidden_arcanus:spawner_scrap')
        .itemIn('forbidden_arcanus:quantum_core')
        .itemOut('forbidden_arcanus:quantum_catcher')

    allthemods.recipes.modern_industrialization.auto_forge(1024, 100)
        .fluidIn('5000x kubejs:liquid_aureal')
        .fluidIn('100x kubejs:liquid_souls')
        .fluidIn('75000x evilcraft:blood')
        .fluidIn('12000x #c:experience')
        .itemIn('minecraft:nether_star')
        .itemIn('3x forbidden_arcanus:stellarite_piece')
        .itemIn('forbidden_arcanus:quantum_catcher')
        .itemOut('forbidden_arcanus:boss_catcher')

    allthemods.recipes.modern_industrialization.auto_forge(1024, 100)
        .fluidIn('5000x kubejs:liquid_aureal')
        .fluidIn('100x kubejs:liquid_souls')
        .fluidIn('60000x evilcraft:blood')
        .itemIn('4x forbidden_arcanus:arcane_crystal')
        .itemIn('4x forbidden_arcanus:spawner_scrap')
        .itemIn('forbidden_arcanus:edelwood_planks')
        .itemIn('forbidden_arcanus:hephaestus_forge_tier_1')
        .itemOut('forbidden_arcanus:hephaestus_forge_tier_2')

    allthemods.recipes.modern_industrialization.auto_forge(1024, 100)
        .fluidIn('10000x kubejs:liquid_aureal')
        .fluidIn('500x kubejs:liquid_souls')
        .fluidIn('90000x evilcraft:blood')
        .itemIn('4x forbidden_arcanus:arcane_crystal')
        .itemIn('4x forbidden_arcanus:deorum_ingot')
        .itemIn('forbidden_arcanus:chiseled_polished_darkstone')
        .itemIn('forbidden_arcanus:hephaestus_forge_tier_2')
        .itemOut('forbidden_arcanus:hephaestus_forge_tier_3')

    allthemods.recipes.modern_industrialization.auto_forge(1024, 100)
        .fluidIn('20000x kubejs:liquid_aureal')
        .fluidIn('1000x kubejs:liquid_souls')
        .fluidIn('120000x evilcraft:blood')
        .itemIn('4x forbidden_arcanus:stellarite_piece')
        .itemIn('4x forbidden_arcanus:rune')
        .itemIn('forbidden_arcanus:chiseled_polished_darkstone')
        .itemIn('forbidden_arcanus:hephaestus_forge_tier_3')
        .itemOut('forbidden_arcanus:hephaestus_forge_tier_4')

    allthemods.recipes.modern_industrialization.auto_forge(1024, 100)
        .fluidIn('50000x kubejs:liquid_aureal')
        .fluidIn('5000x kubejs:liquid_souls')
        .fluidIn('200000x evilcraft:blood')
        .itemIn('4x minecraft:sculk_catalyst')
        .itemIn('2x forbidden_arcanus:dark_nether_star')
        .itemIn('2x forbidden_arcanus:dragon_scale')
        .itemIn('forbidden_arcanus:stellarite_block')
        .itemIn('forbidden_arcanus:hephaestus_forge_tier_4')
        .itemOut('forbidden_arcanus:hephaestus_forge_tier_5')
})
