ServerEvents.recipes(allthemods => {
    allthemods.recipes.modern_industrialization.runic_crucible(32, 100)
        .itemIn('2x forbidden_arcanus:arcane_crystal_dust')
        .fluidIn("1000x starbunclemania:source_fluid")
        .fluidIn("250x minecraft:water")
        .fluidOut('250x kubejs:liquid_aureal')

    allthemods.recipes.modern_industrialization.runic_crucible(32, 100)
        .itemIn('forbidden_arcanus:soul')
        .fluidIn("2000x starbunclemania:source_fluid")
        .fluidIn('500x kubejs:unrefined_liquid_souls')
        .fluidOut('500x kubejs:liquid_souls')

    allthemods.recipes.modern_industrialization.runic_crucible(32, 100)
        .itemIn('forbidden_arcanus:soul')
        .itemIn('reliquary:holy_hand_grenade')
        .fluidIn("2500x starbunclemania:source_fluid")
        .fluidIn('1000x kubejs:liquid_aureal')
        .itemOut('forbidden_arcanus:enchanted_soul')

    allthemods.recipes.modern_industrialization.runic_crucible(32, 100)
        .itemIn('4x forbidden_arcanus:corrupti_dust')
        .itemIn('forbidden_arcanus:soul')
        .itemIn('4x eternal_starlight:trapped_soul')
        .fluidIn("2500x starbunclemania:source_fluid")
        .itemOut('forbidden_arcanus:corrupt_soul')

    allthemods.recipes.modern_industrialization.runic_crucible(32, 150)
        .itemIn('2x #c:dusts/obsidian')
        .itemIn('alltheores:steel_ingot')
        .fluidIn("2500x starbunclemania:source_fluid")
        .fluidIn('500x kubejs:liquid_souls')
        .itemOut('forbidden_arcanus:obsidiansteel_ingot')
})